import = [
    # "~/.config/alacritty/themes/catppuccin-latte.toml"
    "~/.config/alacritty/themes/catppuccin-frappe.toml"
    # "~/.config/alacritty/themes/melange_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
decorations = "Buttonless"

opacity = 1
blur = true

option_as_alt = "Both"

[font]
# normal.family = "BlexMono Nerd Font Mono"
# normal.family = "JetBrainsMono Nerd Font"
# normal.family = "Monaspace Neon Var"
# normal.family = "Fira Code"
normal.family = "Hack Nerd Font Mono"
size = 14
normal.style = "Regular"

# normal.family = "Ubuntu Mono"
# size = 18

