import = [
    "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"

opacity = 1
blur = true

option_as_alt = "Both"

[font]
normal.family = "BlexMono Nerd Font Mono"
normal.style = "Regular"
size = 16

